### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by ghost** [formio/formio-app-basic#5]
$ gulp serve
/Users/dev/node-projects/inrs/formio-app-basic/node_modules/karma/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/dev/node-projects/inrs/formio-app-basic/node_modules/karma/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dev/node-projects/inrs/formio-app-basic/node_modules/karma/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)

**Comment by pavelm** [comment]
+1 I'm seeing the same thing.

**Comment by cegithub** [comment]
I am getting same issue.Is there any solution for this error?

**Comment by randallknutson** [comment]
If you delete the /gulp/e2e-test.js and /gulp/unit-tests.js it will work again. The issue is that karma has deprecated the version in these projects which breaks legacy tests. We aren't using them anyway so they can be removed.

**Comment by hari0206** [comment]
getting this even after adding 'gulp-sass' after removing /gulp/e2e-test.js and /gulp/unit-tests.js
what should I do 
 Starting 'styles'...
[11:44:45] 'styles' errored after 96 ms
[11:44:45] Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at requireFn (E:\formio-app-basic-master2311\node_modules\gulp-load-plugins\index.js:40:16)
    at Object.get (E:\formio-app-basic-master2311\node_modules\gulp-load-plugins\index.js:65:18)
    at Gulp.<anonymous> (E:\formio-app-basic-master2311\gulp\styles.js:41:13)
    at module.exports (E:\formio-app-basic-master2311\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (E:\formio-app-basic-master2311\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (E:\formio-app-basic-master2311\node_modules\orchestrator\index.js:214:10)
[11:44:45] gulp-inject Nothing to inject into index.scss.
[11:44:45] all files 7.08 kB
[11:44:45] Finished 'scripts' after 684 ms
